repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5120']  # 5MB
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-json
      - id: check-toml
      - id: check-xml
  - repo: https://github.com/fredrikekre/runic-pre-commit
    rev: v2.0.1
    hooks:
      - id: runic
        exclude: >-
          (?x)^(
              deps/statements.jl
          )$
