using Spglib
using Bravais: ReciprocalBasis
using Brillouin:
    KPath,
    KPathInterpolant,
    cartesianize,
    latticize,
    latticize!,
    LATTICE,
    CARTESIAN,
    irrfbz_path
using WannierIO: SymbolVec3

export generate_kpath, get_kpoints, generate_w90_kpoint_path

# TODO remove Brillouin.KPath, rename this to KPath
struct RecipPath{T <: Real}
    "Reciprocal lattice vectors (in units of 1/L, where L is unit of length)"
    recip_lattice::Mat3{T}

    "Fractional kpoint coordinates along the kpath"
    points::Vector{Vec3{T}}

    "Indices of high-symmetry kpoints along the kpath"
    indices::Vector{Int}

    "Labels of high-symmetry kpoints"
    labels::Vector{String}
end

function Base.length(kpath::RecipPath)
    return length(kpath.points)
end

struct KSegment{T <: Real}
    "Reciprocal lattice vectors (in units of 1/L, where L is unit of length)"
    recip_lattice::Mat3{T}

    """
    Segments of high-symmetry kpoint path, each segment is a continuous path
    between high-symmetry kpoints. Different segments are disconnected in the
    Brillouin zone.
    """
    segments::Vector{Vector{String}}

    "Coordinates of high-symmetry kpoints"
    coords::Dict{String, Vector{T}}
end

function get_linear_path(kpath::RecipPath)
    kpts_cart = Ref(kpath.recip_lattice) .* kpath.points
    return get_linear_path(kpts_cart, kpath.indices)
end

function RecipPath(recip_lattice::AbstractMatrix, points::AbstractVector, indices::AbstractVector, labels::AbstractVector)
    T = eltype(recip_lattice)
    return RecipPath{T}(
        Mat3{T}(recip_lattice),
        Vector{Vec3{T}}(points),
        Vector{Int}(indices),
        string.(labels),
    )
end

function RecipPath(kpi::KPathInterpolant)
    indices, labels = get_symm_point_indices_labels(kpi)
    recip_lattice = reduce(hcat, kpi.basis)
    T = eltype(recip_lattice)
    return RecipPath{T}(recip_lattice, collect(kpi), indices, labels)
end

function _new_kpath_label(
        label::T, existing_labels::Union{AbstractVector{T}, AbstractSet{T}}
    ) where {T <: Symbol}
    max_tries = 10
    i = 1
    while i < max_tries
        new_label = Symbol(String(label) * "_$i")
        if new_label ∉ existing_labels
            return new_label
        end
        i += 1
    end
    return error("Cannot find a new label?")
end

"""
    $(SIGNATURES)

Construct a `Brillouin.KPath` from the returned `kpoint_path` of `WannierIO.read_win`.

# Arguments
- `lattice`: each column is a lattice vector
- `kpoint_path`: the returned `kpoint_path` of `WannierIO.read_win`, e.g.,
```julia
kpoint_path = [
    [:Γ => [0.0, 0.0, 0.0], :M => [0.5, 0.5, 0.0]],
    [:M => [0.5, 0.5, 0.0], :R => [0.5, 0.5, 0.5]],
]
```
"""
function generate_kpath(
        lattice::AbstractMatrix, kpoint_path::AbstractVector{T}
    ) where {T <: AbstractVector}
    points = Dict{Symbol, Vec3{Float64}}()
    paths = Vector{Vector{Symbol}}()

    warn_str =
        "Two kpoints in `kpoint_path` have the same label but different " *
        "coordinates, appending a number to the label of the 2nd kpoint"

    for path in kpoint_path
        @assert length(path) == 2 "each path should have 2 kpoints"
        k1, k2 = path
        @assert k1 isa Pair && k2 isa Pair "each kpoint should be a `Pair`"
        # start kpoint
        label1 = Symbol(k1.first)
        v1 = Vec3{Float64}(k1.second)
        if label1 ∈ keys(points) && points[label1] ≉ v1
            # convert to Tuple for better printing without type info
            @warn warn_str label = label1 k1 = Tuple(points[label1]) k2 = Tuple(v1)
            label1 = _new_kpath_label(label1, keys(points))
        end
        points[label1] = v1
        # end kpoint
        label2 = Symbol(k2.first)
        v2 = Vec3{Float64}(k2.second)
        if label2 ∈ keys(points) && points[label2] ≉ v2
            @warn warn_str label = label2 k1 = Tuple(points[label2]) k2 = Tuple(v2)
            label2 = _new_kpath_label(label2, keys(points))
        end
        points[label2] = v2
        # push to kpath
        if length(paths) > 0 && label1 == paths[end][end]
            push!(paths[end], label2)
        else
            push!(paths, [label1, label2])
        end
    end

    basis = ReciprocalBasis(eachcol(reciprocal_lattice(lattice)))
    setting = Ref(LATTICE)
    kpath = KPath(points, paths, basis, setting)
    return kpath
end

"""
    $(SIGNATURES)

Generate a `KPathInterpolant` containing kpoint coordinates that are exactly
the same as wannier90.

The kpoints are generated by the following criteria:
- the kpath spacing of remaining segments are kept the same as the first segment
- merge same high-symmetry labels at the corner between two segments; keep both
    labels if the two labels (ending of the 1st segment and starting point of the
    2nd segment) are different

# Arguments
- `kpath`: a `Brillouin.KPath`
- `n_points_first_segment`: number of kpoints in the first segment, remaining
    segments will have the same spacing as the 1st segment.

# Return
- a `KPathInterpolant`.

!!! note

    This reproduce exactly the wannier90 behavior, if
    - the `kpath` is generated by [`generate_kpath`](@ref)
        - the `kpoint_path` argument of `generate_kpath` and be obtained by
            `WannierIO.read_win` which parses the `kpoint_path` block of `win` file
    - the `n_points` is the same as `win` file input parameter `bands_num_points`,
        which again can be obtained by `WannierIO.read_win`.
"""
function generate_w90_kpoint_path(
        kpath::KPath, n_points_first_segment::Integer = default_w90_kpath_num_points()
    )
    # cartesian
    kpath_cart = cartesianize(kpath)
    # kpath spacing from first two kpoints
    k1, k2 = kpath_cart.paths[1][1:2]
    seg = kpath_cart.points[k2] - kpath_cart.points[k1]
    seg_norm = norm(seg)
    dk = seg_norm / n_points_first_segment

    # kpoints along path
    kpaths = Vector{Vector{Vec3{Float64}}}()
    # symmetry points
    labels = Vector{Dict{Int, Symbol}}()

    for path in kpath_cart.paths
        kpaths_line = Vector{Vec3{Float64}}()
        labels_line = Dict{Int, Symbol}()

        n_seg = length(path) - 1
        n_x_line = 0
        for j in 1:n_seg
            k1 = path[j]
            k2 = path[j + 1]

            seg = kpath_cart.points[k2] - kpath_cart.points[k1]
            seg_norm = norm(seg)

            n_x_seg = Int(round(seg_norm / dk))
            # ensure at least the two ending points are there, if the seg_norm is too small
            n_x_seg = max(n_x_seg, 1)
            x_seg = collect(range(0, seg_norm, n_x_seg + 1))
            dvec = iszero(seg_norm) ? seg : seg / seg_norm

            # column vector * row vector = matrix
            kpt_seg = dvec * x_seg'
            kpt_seg .+= kpath_cart.points[k1]

            if j == 1
                push!(labels_line, 1 => k1)
            else
                # remove repeated points
                popfirst!(x_seg)
                kpt_seg = kpt_seg[:, 2:end]
            end
            n_x_line += length(x_seg)
            push!(labels_line, n_x_line => k2)

            append!(kpaths_line, [v for v in eachcol(kpt_seg)])
        end

        push!(kpaths, kpaths_line)
        push!(labels, labels_line)
    end

    basis = kpath.basis
    setting = Ref(CARTESIAN)
    kpi = KPathInterpolant(kpaths, labels, basis, setting)
    # to fractional
    latticize!(kpi)

    return kpi
end

function generate_w90_kpoint_path(
        lattice::AbstractMatrix,
        kpoint_path::AbstractVector{T},
        n_points_first_segment::Integer = default_w90_kpath_num_points(),
    ) where {T <: AbstractVector}
    kpath = generate_kpath(lattice, kpoint_path)
    return generate_w90_kpoint_path(kpath, n_points_first_segment)
end

function generate_kpath(kpi::KPathInterpolant)
    points = Dict{Symbol, Vec3{Float64}}()
    paths = Vector{Vector{Symbol}}()

    for (label, path) in zip(kpi.labels, kpi.kpaths)
        ik_labels = sort(pairs(label); by = first)
        push!(paths, collect(values(ik_labels)))
        for (ik, lab) in pairs(ik_labels)
            points[lab] = path[ik]
        end
    end

    kpath = KPath(points, paths, kpi.basis, kpi.setting)

    return kpath
end

"""
    $(SIGNATURES)

Convert labels of high-symmetry kpoints to unicode string.

e.g., `GAMMA` -> `Γ`, `DELTA_0` -> `Δ₀`
"""
function symm_label_to_unicode(labels::AbstractVector{<:AbstractString})
    label_maps = Dict(
        "GAMMA" => "Γ",
        "DELTA" => "Δ",
        "LAMBDA" => "Λ",
        "SIGMA" => "Σ",
        "0" => "₀",
        "1" => "₁",
        "2" => "₂",
        "3" => "₃",
        "4" => "₄",
        "5" => "₅",
        "6" => "₆",
        "7" => "₇",
        "8" => "₈",
        "9" => "₉",
    )
    return map(labels) do l
        if occursin("_", l)
            base, sub = split(l, "_"; limit = 2)
            return get(label_maps, base, base) * get(label_maps, sub, sub)
        end
        return get(label_maps, l, l)
    end
end

"""
    $(SIGNATURES)

Merge consecutive high-symmetry points.

If two high-symmetry kpoints are neighbors, merge them into one.

# Arguments
- `indices`: indices of high-symmetry kpoints, start from 1

# Return
- `idxs`: a vector of vectors, if the inner vector contains more than 1 index,
    it means those indices are neighbors and are merged.
    For example, if the input `indices` is `[1, 2, 4, 5, 6]`, the output will be
    `[[1, 2], [4, 5, 6]]`.
"""
function merge_symm_indices(indices::AbstractVector{<:Integer})
    isempty(indices) && return indices
    idxs = [eltype(indices)[]]
    push!(idxs[1], indices[1])

    counter = 2
    for i in eachindex(indices)[2:end]
        if indices[i] == indices[i - 1] + 1
            push!(idxs[counter - 1], indices[i])
        else
            push!(idxs, [indices[i]])
            counter += 1
        end
    end

    return idxs
end

"""
    $(SIGNATURES)

Merge consecutive high-symmetry points.

If two high-symmetry kpoints are neighbors, merge them into one,
with label `X|Y`, where `X` and `Y` are the original labels of
the two kpoints, respectively.

# Arguments
- `indices`: indices of high-symmetry kpoints, start from 1
- `labels`: labels of high-symmetry kpoints
"""
function merge_symm_labels(
        indices::AbstractVector{<:Integer},
        labels::AbstractVector{<:AbstractString},
    )
    idxs = merge_symm_indices(indices)
    labs = map(idxs) do is
        js = map(is) do i
            findfirst(==(i), indices)
        end
        join(labels[js], "|")
    end
    jdxs = isempty(idxs) ? idxs : first.(idxs)
    return jdxs, labs
end

function merge_linear_path(kpath::AbstractVector{<:Real}, indices::AbstractVector{<:Integer})
    idxs = merge_symm_indices(indices)
    for is in idxs
        (length(is) > 1) || continue
        for j in is[2:end]
            δ = kpath[j] - kpath[j - 1]
            kpath[j:end] .-= δ
        end
    end
    return kpath
end

function get_linear_path(
        kpoints_cart::AbstractVector{<:AbstractVector{<:Real}},
        indices::AbstractVector{<:Integer} = [],
    )
    kpath = [0.0; accumulate(+, norm.(diff(kpoints_cart)))]
    kpath = merge_linear_path(kpath, indices)
    return kpath
end

"""
    $(SIGNATURES)

Get a 1D vector of distance from the 1st kpoint along the kpath.

# Arguments
- `kpi`: a `KPathInterpolant`

# Return
- `x`: a vector containing the distance of each kpoint w.r.t. the 1st kpoint.
    Can be used as the x-axis value for plotting band structures, in Cartesian length.
"""
function get_linear_path(kpi::KPathInterpolant)
    kpi_cart = cartesianize(kpi)
    x = Vector{Float64}()

    for path in kpi_cart.kpaths
        n_points = length(path)

        push!(x, 0)
        for j in 2:n_points
            k1 = path[j - 1]
            k2 = path[j]
            dx = norm(k2 - k1)
            push!(x, dx)
        end
    end

    return cumsum(x)
end

"""
    $(SIGNATURES)

Get the kpoints coordinates from a `KPathInterpolant`.

# Arguments
- `kpi`: `KPathInterpolant`

# Return
- `kpoints`: a length-`n_kpoints` vector, each element is a kpath kpoint
    fractional coordinates
"""
function get_kpoints(kpi::KPathInterpolant)
    return map(latticize(kpi)) do k
        Vec3(k)
    end
end

"""
    $(SIGNATURES)

This function returns the input `kpoints` as is.

!!! note

    This is used in the [`AbstractTBInterpolator`](@ref), since it is not
    possible to define a function like this:
    ```julia
    @inline function (interp::AbstractTBInterpolator)(kpi::KPathInterpolant; kwargs...)
        kpoints = get_kpoints(kpi)
        return interp(kpoints; kwargs...)
    end
    ```
    because this will cause method ambiguity:
    - the `KPathInterpolant` is also a `AbstractVector{<:AbstractVector}`
    - each concrete interpolator type defines a function for `AbstractVector{<:AbstractVector}`

    Therefore, we define this function so that all the Interpolators can handle
    both `AbstractVector{<:AbstractVector}` (for fractional coordinates)
    and `KPathInterpolant`.
"""
function get_kpoints(kpoints::AbstractVector{T}) where {T <: AbstractVector}
    return kpoints
end

"""
    $(SIGNATURES)

Get a `Brillouin.KPath` for arbitrary cell (can be non-standard).

Internally use `Brillouin.jl`.

# Arguments
- `lattice`: `3 * 3`, each column is a lattice vector
- `atom_positions`: `3 * n_atoms`, fractional coordinates
- `atom_numbers`: `n_atoms` of integer, atomic numbers
"""
function generate_kpath(
        lattice::AbstractMatrix, atom_positions::AbstractVector, atom_numbers::AbstractVector{T}
    ) where {T <: Integer}
    vecs = [v for v in eachcol(lattice)]
    cell = Spglib.Cell(vecs, Vector.(atom_positions), atom_numbers)
    kpath = irrfbz_path(cell)
    return kpath
end

"""
    $(SIGNATURES)

Get a `Brillouin.KPath` for arbitrary cell (can be non-standard).

Internally use `Brillouin.jl`.

# Arguments
- `lattice`: `3 * 3`, each column is a lattice vector
- `atom_positions`: `3 * n_atoms`, fractional coordinates
- `atom_labels`: `n_atoms` of string, atomic labels
"""
function generate_kpath(
        lattice::AbstractMatrix, atom_positions::AbstractVector, atom_labels::AbstractVector{T}
    ) where {T <: AbstractString}
    atom_numbers = get_atom_number(atom_labels)
    return generate_kpath(lattice, atom_positions, atom_numbers)
end

"""
    $(SIGNATURES)

Generate a `KPath` for the `Model`.
"""
function generate_kpath(model::Model)
    return generate_kpath(model.lattice, model.atom_positions, model.atom_labels)
end
