using Documenter
using Wannier
# using WannierPlots

# The processing of examples take quite some time. To speed up development,
# set this flag to true to skip them.
# SKIP_EXAMPLES = false
SKIP_EXAMPLES = true

# The examples are auto-generated by Literate.jl.
# Here you can specify the name of tutorial page shown in the left sidebar,
# by changing the key of the pair.
EXAMPLES = [
    "Maximal localization" => "examples/maximal_localization.md",
    "Disentanglement" => "examples/disentanglement.md",
    "Band structure" => "examples/band_structure.md",
    "Real space WF" => "examples/realspace_wf.md",
    "Parallel transport" => "examples/parallel_transport.md",
    "Parallel transport with custom b-vectors" => "examples/parallel_transport_bvectors.md",
    "Split valence/conduction" => "examples/manifold_remixing.md",
    "Constrain WF center" => "examples/center_constraint.md",
    "Fermi surface" => "examples/fermi_surface.md",
    # "Spin texture" => "examples/spin_texture.md",
    # "Cooptimize spin-polarized WFs" => "examples/10-coopt.md",
    "Tips & code snippets" => "examples/code_snippets.md",
]

# Delete previous examples to do a clean build.
# Otherwise, even if I comment out some entries in `EXAMPLES`, the old pages
# will still be process by Documenter.jl.
LITERATE_EXAMPLES_OUTDIR = joinpath(@__DIR__, "src/examples")
isdir(LITERATE_EXAMPLES_OUTDIR) && rm(LITERATE_EXAMPLES_OUTDIR; recursive=true)

# Process examples by Literate.jl
if SKIP_EXAMPLES
    examples_pages = []
else
    include("literate.jl")

    # Add numbers to the examples
    examples_pages = map(enumerate(EXAMPLES)) do (i, (name, path))
        (string(i) * " " * name) => path
    end

    # Add Foreword page
    insert!(examples_pages, 1, "Foreword" => "examples_foreword.md")
end

# generate the HTML pages by Documenter.jl
makedocs(;
    sitename="Wannier.jl",
    authors="Junfeng Qiao and contributors.",
    clean=true,
    modules=[Wannier],
    pages=[
        "Home" => "index.md",
        "Getting Started" => "start.md",
        "Examples" => examples_pages,
        "Theory" => [
            "Normalization" => "theory/normalization.md",
            "``k``-space Discretization" => "theory/discretization.md",
            "Initial projection" => "theory/initial_projection.md",
            "Localization" => "theory/algorithm.md",
            "Wannier Interpolation" => "theory/fourier.md",
        ],
        "API" => [
            "Utility" => "api/util.md",
            "Input/Output" => "api/io.md",
            "Model" => "api/model.md",
            "``b``-vector" => "api/bvector.md",
            "Localization" => "api/wannierize.md",
            "Real space" => "api/realspace.md",
            "Interpolation" => "api/interpolation.md",
        ],
    ],
)

# Documenter will auto dectect build environment; on local machine it will be
# skipped, so it's safe to run this script
deploydocs(; repo="github.com/qiaojunfeng/Wannier.jl.git", devbranch="main")
